// Package iso8583 provides marshal and unmarshal functionality for ISO-8583 messages.
//
// Example Marshal Usage
//
// type PurchaseRequest struct {
//	MTI                    field.MTI    `iso8583:"mti"`
//	FirstBitmap            field.BITMAP `iso8583:"bitmap,length:64"` // length is the maximum amount of represented elements.
//	SecondBitmap           field.BITMAP `iso8583:"1,length:64"`      // length is the maximum amount of represented elements.
//	PAN                    field.LLVAR  `iso8583:"2"`
//	ProcessingCode         field.VAR    `iso8583:"3"`
//	Amount                 field.VAR    `iso8583:"4,encoding:ebcdic"` // By default ASCII is assumed but dont limit yourself!
//	DateTime               field.VAR    `iso8583:"7"`
//	SystemTraceAuditNumber field.VAR    `iso8583:"11,omitempty"` // omitempty is supported!
//	LocalTransactionTime   field.VAR    `iso8583:"12"`
//	LocalTransactionDate   field.VAR    `iso8583:"-"` // You can explicitly ignore a field.
//	ExpirationDate         field.VAR    `iso8583:"14"`
//	MerchantType           field.VAR    `iso8583:"18"`
//	ICC                    field.LLLVAR `iso8583:"55"`
//	SettlementCode         field.VAR    `iso8583:"66"`
//	MessageNumber          field.VAR    `iso8583:"71"`
//	TransactionDescriptor  field.VAR    `iso8583:"104"`
// }
//
// func GenerateStaticReqBytes() ([]byte, error) {
//	req := PurchaseRequest{
//		MTI: "0100",
//		// FirstBitmap is generated by library
//		// SecondBitmap is generated by library
//		PAN: "54000000000000111", // LL part is added by library!
//		ProcessingCode: "1000",
//		Amount: "000000000100",
//		MessageNumber: "1",
//	}
//
//	byt, err := iso8583.Marshal(req)
//	if err != nil {
//		return nil, err
//	}
//
//	return byt, nil
// }
//
// Example Unmarshal Usage
//
// type PurchaseResponse struct {
//	MTI                    field.MTI    `iso8583:"mti,length:4"`
//	FirstBitmap            field.BITMAP `iso8583:"bitmap,length:64"` // length is the maximum amount of represented elements.
//	SecondBitmap           field.BITMAP `iso8583:"1,length:64"`      // length is the maximum amount of represented elements.
//	PAN                    field.LLVAR  `iso8583:"2,length:2"`       // length is the amount of bytes of the LL part.
//	ProcessingCode         field.VAR    `iso8583:"3,length:6"`
//	Amount                 field.VAR    `iso8583:"4,length:12"`
//	DateTime               field.VAR    `iso8583:"7,length:10"`
//	SystemTraceAuditNumber field.VAR    `iso8583:"11,length:6"`
//	LocalTransactionTime   field.VAR    `iso8583:"12,length:6"`
//	LocalTransactionDate   field.VAR    `iso8583:"13,length:4"`
//	ExpirationDate         field.VAR    `iso8583:"14,length:4"`
//	MerchantType           field.VAR    `iso8583:"18,length:4"`
//	ResponseCode           field.VAR    `iso8583:"39,length:2"`
//	ICC                    field.LLLVAR `iso8583:"55,length:3,encoding:ebcdic/ascii"` // LLL and VAR part use different encoding? Use a / to indicate both
//	SettlementCode         field.VAR    `iso8583:"66,length:1"`
//	MessageNumber          field.VAR    `iso8583:"71,length:4"`
//	TransactionDescriptor  field.VAR    `iso8583:"104,length:100"`
// }
//
// func ReadResp(byt []byte) (PurchaseResponse,error){
//	var resp PurchaseResponse
//
//	_, err :=iso8583.Unmarshal(byt,&resp)
//	if err != nil{
//		return PurchaseResponse{}, err
//	}
//
//	return resp,nil
// }
// Assertions
//
// This packages includes interfaces to allow developers to add new fields
// with custom behavior.

package iso8583