language: go

go:
  - 1.13.x
  - 1.14.x

before_install:
  - go get -t -v ./...
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0

script:
  - make

after_success:
  - bash <(curl -s https://codecov.io/bash)