language: go

go:
  - 1.16.x
  - 1.15.x
  - 1.14.x
  - 1.13.x

install: true

services:
  - docker

before_install:
  - go get -t -v ./...
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0

script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
  - bash .ci/make.sh
  - bash .ci/gofmt.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)